---

- name: discover our filtered instance to clone
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"
    region: "{{region}}"
    filters:
      "tag:Name": "{{student}}-ansible-linux-1"
  register: output

- debug:
    msg: "ec2 instance ID is {{output.instances[0].instance_id}}"
    verbosity: 1

- name: create a custom AMI
  ec2_ami:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"
    region: "{{region}}"
    instance_id: "{{output.instances[0].instance_id}}"
    wait: no
    name: "{{student}}_ami"
    tags:
      myami: "{{student}}_ami"
