---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: "eu-west-2"
  vars_files:
    - ../aws_keys.yml

  tasks:

    - name: Find latest RedHat Linux AMI to use
      ec2_ami_find:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{region}}"
        name: "RHEL-7.6_HVM_GA*"
        owner: 309956199498 
        sort: name
        sort_order: descending
        sort_end: 1
      register: ami_find

    - debug:
        msg: "This is the AMI ID {{ami_find.results[0].ami_id}}"
        verbosity: 1

    - name: Save the AMI ID so we can re-use
      set_fact:
        ami_id: "{{ami_find.results[0].ami_id}}"

    - name: Launch LINUX instance(s)
      vars:
        security_group: "{{student}}_sg"
        ami_id: "{{ami_id}}"
        ec2_instance_name: ansible-linux
        os: linux
        remote_port: 22 
        keypair: aws-workshop
        instance_count: 2

      ec2_instance:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        security_token: "{{security_token}}"
        name: "{{student}}-ansible-{{os}}-{{item}}"
        security_group: "{{security_group}}"
        key_name: "{{keypair}}"
        network:
          assign_public_ip: true
        image_id: "{{ami_id}}"
        region: "{{region}}"
        tags:
          student: "{{student}}"
      with_sequence: count="{{instance_count}}"
      register: ec2_instances
