---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: "eu-west-2"
  vars_files:
    - ../aws_keys.yml

  tasks:

    - name: gather ec2 instances
      ec2_instance_facts:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        security_token: "{{security_token}}"
        region: "{{region}}"
        filters:
          instance-state-name: "running"
          "tag:student": "{{student}}"
      register: instances

    - name: ensure we have SSH access
      wait_for:
        host: "{{item.public_ip_address}}"
        port: 22
        timeout: 300
      with_items: "{{instances.instances}}"

    - name: add instance to temp inventory
      add_host:
        hostname: "{{item.public_ip_address}}"
        groups: webservers
        ansible_connection: ssh
        ansible_user: ec2-user
      with_items: "{{instances.instances}}"

- hosts: webservers
  become: yes
  become_method: sudo

  vars:
    web_message: "ROCK and ROLL BABY!!"

  tasks:

    - name: install httpd 
      yum:
        name: httpd
        state: latest

    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Check if firewalld is running
      shell: systemctl is-active firewalld
      register: firewall_status
      ignore_errors: true

    - name: Open firewall ports for httpd
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true
      when: firewall_status.stdout == 'active'

    - name: Configure Web Content
      template: 
        dest: /var/www/html/index.html 
        src: index.html.j2
